// Command inject instruments a Go module for `sem system`'s dynamic layer:
// every function and closure body in the module's non-test, non-vendor files
// gets `systrace.Hit()` as its first statement, which records the calling
// frame and the callee once per distinct pair to $SYSTRACE_OUT/go-<pid>.jsonl.
//
// Edits are textual and line-preserving: the hook goes right after the
// body's `{`, and the import joins the package clause's line, so every
// recorded line number matches the untouched source the static layers read.
//
// Usage: go run inject.go [-vendor] <module dir>   (run on a scratch copy)
//
// With -vendor, packages under vendor/ (after `go mod vendor`) are
// instrumented too, so calls from the module into its dependencies are
// recorded; the tests then run with -mod=vendor. It also prints
// `vendor/<module>=<module>@<version>` lines (from vendor/modules.txt) for
// mapping recorded paths back to the module cache.
package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const helper = `// Code generated by sem system inject. DO NOT EDIT.
package zz_systrace

import (
	"fmt"
	"os"
	"runtime"
	"sync"
)

var (
	seen sync.Map
	mu   sync.Mutex
	out  *os.File
	tried bool
)

func file() *os.File {
	if !tried {
		tried = true
		if dir := os.Getenv("SYSTRACE_OUT"); dir != "" {
			_ = os.MkdirAll(dir, 0o755)
			out, _ = os.OpenFile(fmt.Sprintf("%s/go-%d.jsonl", dir, os.Getpid()), os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0o644)
		}
	}
	return out
}

// Hit records (caller frame, callee frame) once.
func Hit() {
	var pcs [4]uintptr
	n := runtime.Callers(2, pcs[:])
	if n < 2 {
		return
	}
	key := [2]uintptr{pcs[0], pcs[1]}
	if _, loaded := seen.LoadOrStore(key, struct{}{}); loaded {
		return
	}
	frames := runtime.CallersFrames(pcs[:n])
	callee, more := frames.Next()
	if !more {
		return
	}
	caller, _ := frames.Next()
	line := fmt.Sprintf("{\"caller_file\":%q,\"site_line\":%d,\"caller\":%q,\"callee_file\":%q,\"callee_line\":%d,\"callee\":%q}\n",
		caller.File, caller.Line, caller.Function, callee.File, callee.Line, callee.Function)
	mu.Lock()
	if f := file(); f != nil {
		_, _ = f.WriteString(line)
	}
	mu.Unlock()
}
`

func modulePath(dir string) string {
	b, err := os.ReadFile(filepath.Join(dir, "go.mod"))
	if err != nil {
		return ""
	}
	for _, l := range strings.Split(string(b), "\n") {
		l = strings.TrimSpace(l)
		if strings.HasPrefix(l, "module ") {
			return strings.Trim(strings.TrimSpace(strings.TrimPrefix(l, "module ")), "\"")
		}
	}
	return ""
}

func main() {
	vendor := flag.Bool("vendor", false, "also instrument vendor/")
	flag.Parse()
	if flag.NArg() != 1 {
		fmt.Fprintln(os.Stderr, "usage: inject [-vendor] <module dir>")
		os.Exit(2)
	}
	root, _ := filepath.Abs(flag.Arg(0))
	mod := modulePath(root)
	if mod == "" {
		fmt.Fprintln(os.Stderr, "no go.mod module in", root)
		os.Exit(2)
	}
	if err := os.MkdirAll(filepath.Join(root, "zz_systrace"), 0o755); err != nil {
		panic(err)
	}
	if err := os.WriteFile(filepath.Join(root, "zz_systrace", "systrace.go"), []byte(helper), 0o644); err != nil {
		panic(err)
	}
	files, funcs := 0, 0
	_ = filepath.Walk(root, func(p string, info os.FileInfo, err error) error {
		if err != nil {
			return nil
		}
		if info.IsDir() {
			name := info.Name()
			inVendor := strings.Contains(p+"/", "/vendor/")
			if p != root && ((name == "vendor" && !*vendor) || name == "testdata" || name == "zz_systrace" || strings.HasPrefix(name, ".") || name == "node_modules") {
				return filepath.SkipDir
			}
			// a nested module is instrumented by its own run
			if p != root && !inVendor {
				if _, err := os.Stat(filepath.Join(p, "go.mod")); err == nil {
					return filepath.SkipDir
				}
			}
			return nil
		}
		if !strings.HasSuffix(p, ".go") || strings.HasSuffix(p, "_test.go") {
			return nil
		}
		n, ok := instrument(p, mod)
		if ok {
			files++
			funcs += n
		}
		return nil
	})
	fmt.Fprintf(os.Stderr, "instrumented %d functions in %d files (module %s)\n", funcs, files, mod)
	if *vendor {
		b, _ := os.ReadFile(filepath.Join(root, "vendor", "modules.txt"))
		for _, l := range strings.Split(string(b), "\n") {
			f := strings.Fields(l)
			if len(f) >= 3 && f[0] == "#" && strings.HasPrefix(f[2], "v") {
				fmt.Printf("vendor/%s=%s@%s\n", f[1], f[1], f[2])
			}
		}
	}
}

func instrument(path, mod string) (int, bool) {
	src, err := os.ReadFile(path)
	if err != nil {
		return 0, false
	}
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, path, src, parser.ParseComments)
	if err != nil {
		return 0, false
	}
	var inserts []int
	ast.Inspect(f, func(n ast.Node) bool {
		switch x := n.(type) {
		case *ast.FuncDecl:
			if x.Body != nil && !pragma(x.Doc) {
				inserts = append(inserts, fset.Position(x.Body.Lbrace).Offset+1)
			}
		case *ast.FuncLit:
			inserts = append(inserts, fset.Position(x.Body.Lbrace).Offset+1)
		}
		return true
	})
	if len(inserts) == 0 {
		return 0, false
	}
	// the import joins the package clause's line
	pkgEnd := fset.Position(f.Name.End()).Offset
	edits := map[int]string{pkgEnd: "; import systrace \"" + mod + "/zz_systrace\""}
	for _, off := range inserts {
		edits[off] = "systrace.Hit();"
	}
	offs := make([]int, 0, len(edits))
	for o := range edits {
		offs = append(offs, o)
	}
	sort.Sort(sort.Reverse(sort.IntSlice(offs)))
	out := string(src)
	for _, o := range offs {
		out = out[:o] + edits[o] + out[o:]
	}
	if err := os.WriteFile(path, []byte(out), 0o644); err != nil {
		return 0, false
	}
	return len(inserts), true
}

// pragma reports compiler directives under which an inserted call is unsafe.
func pragma(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}
	for _, c := range doc.List {
		for _, p := range []string{"//go:nosplit", "//go:linkname", "//go:noescape", "//go:nowritebarrier", "//go:systemstack", "//go:norace"} {
			if strings.HasPrefix(c.Text, p) {
				return true
			}
		}
	}
	return false
}
